### ISSUE TITLE
Corrección

### ISSUE THREAD

**Issue by chavisam** [orosell666/generatedomain-exercise#1]
Hola Oriol. 

El ejercicio no está bien, porque al cargar el index.html no pasa absolutamente nada. 
Eso se debe a que has creado el archivo getdomain.js  y no lo has cargado en el index.html 

El objetivo es que al cargar el index.html  te aparezcan todos los dominios en la pantalla. 
Cuando lo tengas.... avísame por slack

Saludos
Chavi

**Comment by orosell666** [comment]
Hola Chavi,

Marcos nos indico de entregar el ejercicio así, que ya estaba bien, de
hecho nos ayudo él a subirlo a github.
Si eso luego pruebo de hacer lo que me dices y te aviso!



El dt., 25 de gen. 2022, 22:53, Javier Manteca (Chavi) <
***@***.***> va escriure:
